### ISSUE TITLE
Log Error:  "The "--" option does not exist." 

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#10]
When I try to Execute again import nothing happend.

![image](https://user-images.githubusercontent.com/7449124/153346943-8b0615aa-0791-4283-84c5-16986acd3ecd.png)

I checked log and I see error there:

`[2022-02-10 06:52:09] console.CRITICAL: Error thrown while running command "data-director:process 2 0 --force -vv--dataport-resource-id=26 --user=2". Message: "The "--" option does not exist." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--\" option does not exist. at /var/www/pimcore.dev/www/vendor/symfony/symfony/src/Symfony/Component/Console/Input/ArgvInput.php:118)","command":"data-director:process 2 0 --force -vv--dataport-resource-id=26 --user=2","message":"The \"--\" option does not exist."} []`

**Comment by BlackbitNeueMedien** [comment]
Thanks, there was a whitespace missing. Fixed in 2.8

**Comment by betterapp** [comment]
Is 2.8 have a tag ? Because we see 2.7.10 as latest.

**Comment by BlackbitNeueMedien** [comment]
Is shortly before being released. You can use `2.8.x-dev` as composer.json version constraint.

**Comment by betterapp** [comment]
when 2.8 will be released ?

**Comment by BlackbitNeueMedien** [comment]
Release date is not fixed. When I have long enough not heard of any bugs from clients who use 2.8
