### ISSUE TITLE
DD for PimCore 11

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#100]
Hi.

Will DataDirector work with PimCore 11 ?

**Comment by ascheider** [comment]
I have the same question. Is there any timeline when data director will be compatible with pimcore 11?
We want to schedule some pimcore updates and waiting for compatibility.
Thanks!

**Comment by BlackbitDevs** [comment]
We have started to implement Pimcore 11 compatibility while still keeping everything up-to-date with older Pimcore versions (Data Director's strategy was always to be achieve maximum compatibility so that all DD features are available independent of what Pimcore version you use). But currently there is too much other projects. Of course it will help if you contact info@blackbit.de to prioritize this.

**Comment by BlackbitDevs** [comment]
Branch 3.5 is now compatible with Pimcore 11. Currently we are testing it and soon it will be released. @ascheider / @betterapp would be great if you also could do some testing with `3.5.x-dev`

**Comment by ascheider** [comment]
@BlackbitDevs Thank you very much. We will test it next week and give you feedback. Should i create new issues if i find bugs, or report it here?

**Comment by BlackbitDevs** [comment]
@ascheider Please report bugs here.

**Comment by BlackbitDevs** [comment]
@patrickpahlke03 Thanks a lot!

Have adjusted the code like this:
```php
$reportAdapterConfig = ['custom_report' => ['adapters' => ['dataDirector' => 'pimcore.custom_report.adapter.factory.dataDirector']]];
        if(version_compare(Helper::getPimcoreVersion(), '11', '<')) {
            foreach ($container->getExtensions() as $name => $extension) {
                if ($name === 'pimcore') {
                    $container->prependExtensionConfig($name, $reportAdapterConfig);
                }
            }
        } elseif (isset($bundles['PimcoreCustomReportsBundle'])) {
            foreach ($container->getExtensions() as $name => $extension) {
                if ($name === 'pimcore_custom_reports') {
                    $container->prependExtensionConfig($name, $reportAdapterConfig['custom_report']);
                }
            }
        }
```
So basically it removes the additional `custom_report` on top level. Can you please check?

**Comment by patrickpahlke03** [comment]
@BlackbitDevs It works as expected. Thanks

**Comment by ascheider** [comment]
@BlackbitDevs Patrick did not found any problems anymore, but i did found one more problem.
If i run doctrine:migrations:migrate to upgrade pimcore, i get following error.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/33ad846a-f922-4d47-a45c-893e7c55626a)
The method addPathFormatterService is called on brick saving and has wrong Class as parameter.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/bbc0aa9a-8ebc-4880-90b0-e7cf88819766)
I'm using latest version of branch 3.5

**Comment by ascheider** [comment]
@BlackbitDevs One more thing, not sure why it's happening. The AdminStyleListener sets everything to root htdocs/vendor/blackbit/data-director/EventListener/AdminStyleListener.php
If i remove the line:  $event->setAdminStyle(new GridViewFieldsAdminStyle($event->getElement(), $this->translator, $event->getAdminStyle())); i can see normal folder names.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/1078f0a9-4e34-4681-8ffd-b9adb8698852)
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/40014011-e18e-45ad-8ae6-e5fe5d113747)
After i remove the line:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/daeaee85-06a0-4a01-9ac3-2ef90afe53d8)

**Comment by ascheider** [comment]
Renaming asset folder with PHP 8.2 throws exception
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/27ce19f6-d87d-4dca-a96e-d72983230b32)

**Comment by BlackbitDevs** [comment]
@ascheider Is fixed. I suspect that this bug also existed in Pimcore 10. But anyway, is fixed now.
