### ISSUE TITLE
Strange logs on DataPort

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#103]
Hello

We have one Data Port which import data from files located under specific folder path.
The configurations looks like this:

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/bb6c3eb1-7a4b-4990-8172-5ff72e1de048)

It is running automatically on new data. SO it should run only new files appears in folder which match settigs.

But we have strange logs.
Every different period of time we see something like this:

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/891ed090-4aef-4a97-8096-4762780b18e3)

Why we have this additional logs ?

We use DD: 3.2.39

**Comment by BlackbitDevs** [comment]
How the checkbox "Run automatically on new data" works, depends on the import resource type. For elements which trigger an event, the dataport will get run event-based. For import resources where changes do not trigger an event, the dataport gets run together with the maintenance job. 
And currently there seems to be a bug in this check if the import resource can be checked based on event. Your import resource is a Pimcore asset path (with glob expression), right?
Will fix this...

**Comment by BlackbitDevs** [comment]
Is fixed in 3.4. 
Do you need this for 3.2 / 3.3?

**Comment by betterapp** [comment]
Yes. Please

**Comment by BlackbitDevs** [comment]
Fix is also released in 3.2.40 and 3.3.21
