### ISSUE TITLE
Brick import with 0 integer values

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#104]
Currently it is not possible to import brick if mapped value is equals 0 because of following code in Importer.php:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/4be68cf5-e245-4bac-bf5a-32a5a35abe8f)
If you dump variables, then integer zero is casted to float 0 and empty returns true, so brick creation is skipped:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/7a6e94d8-08b2-4d42-b616-17e950494b98)
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/5e2c11df-5c04-4ea1-8b1e-e087b014aaf7)
If i change value to 100 for example and rerun import:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/b03e1a14-910d-4084-a399-1400930d71cb)
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/43e12a4a-40dc-4eb6-8543-7312f38d4584)
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/412decb7-07a3-47ae-868a-91ab039c647b)
So the valid integer value can currently not be imported in bricks. I don't know if the problem also exists in another importer areas. Empty is heavely used in importer.php

Files to reproduce (as txt github does not allow json):
[objectbrick_CF00010_export.txt](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/11832825/objectbrick_CF00010_export.txt)
[class_TestClass_export.txt](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/11832826/class_TestClass_export.txt)
[importtest.txt](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/11832830/importtest.txt)

**Comment by BlackbitDevs** [comment]
Thanks for your detailed report. Is fixed in 3.4.3. Can you please check and close this issue, if it now works as expected?

**Comment by ascheider** [comment]
@BlackbitDevs Works now. Thanks!
