### ISSUE TITLE
Export error if field name has apostrophe

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#107]
The customer has object brick with some usp's
After click on auto create, the config for the export is created:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/e4cfa2e9-9098-4f08-a31d-346ac76547e5)
Ich you select excel in result callback function, data director does not escape the apostrophe with backslash for example.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/84820099-e5a8-4e33-be98-e2da510e4b79)
If you run the export, you get the exception in eval:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/b61a0dee-0da2-461c-a9db-5403e1b69330)

In my opinion:
1.) you can strip the apostrophe from field name
2.) strip apostrophe in template creation

**Comment by BlackbitDevs** [comment]
Beside that "USP's" is not the correct plural of "USP", you are right ;-)

Now in both places (auto-create fields and result callback function template generation) all non-alphanumeric characters (except whitespace) get replaced.

Released as 3.4.10.

**Comment by ascheider** [comment]
@BlackbitDevs Thanks for the quick fix ;)
