### ISSUE TITLE
Filter condition from store table

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#112]
Hello

We have Data Port and filter condition like this:

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/5f848764-26b0-48b1-b6a1-794bb6c90878)

As I know this filter condition use query table.

Is it possible to use somehow store table for specified field ?

**Comment by BlackbitDevs** [comment]
There is a checkbox directly above the `filter condition` field to configure if inheritance shall be used for the database queries (aka if `query` or `store` tables should be used):
<img width="1005" alt="Bildschirmfoto 2023-08-02 um 15 58 33" src="https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/8749138/5e0b616a-6e06-4410-b71b-5facb90ec065">

Currently there is no convenience helper to filter a single field from the `store` table why other condition parts use the `query` table. But of course you could do this with a subselect.

If you do not want to use a subselect you could remove the `SendToSAP = '1'` condition part and add a raw data field with data query selector `withoutInheritance:SendToSAP`. Then in attribute mapping you could check its value skip this item if value != 1. But of course this will cause quite a high load as the raw data processing then gets started also for objects which would have been filtered out by the `SendToSAP = '1'` SQL condition right at the beginning.

So I would recommend to disable the `Using inheritance` checkbox if the whole query shall be based in `store` table. And if not, I would use a subselect.
