### ISSUE TITLE
Step 2 - problem

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#115]
We have dataport that return some data via API call.

Step one is ok.
But when it start Step 2 we see something like this:

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/1c29f815-b6c0-45a7-966f-531e4b4e809d)

and when this row (last on list) disappear there is no information about Step 2.

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/296d8bfb-ca15-47c4-996f-75f61563dcd8)

When I remove Row Data on Preview panel and run this DataPort again - it is working fine. I have information about
those 2 steps.

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/2e4c3900-f4b0-4f68-aa94-b802c3deb186)

But it working only once.
When I try to get data again - we have this strange behavior.

DD: 3.2.25
PIM: 6.9

Should we update DD to never version or what ?

**Comment by Jan-Walther-Blackbit** [comment]
> Should we update DD to never version or what ?
Yes, at least you could check on a dev instance if the problem still occurs. Imho it does not make sense to look for a bug which may have been fixed in current stable versions anyway.
