### ISSUE TITLE
Identify field collection item for the import

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#118]
we have a field collection which is named Pcm
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/c652642f-6b8c-44bd-ad64-7ecd8924edfa)
The collection contains some fields which are imported:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/478722f3-042e-44df-a635-d6cdf5190a89)
If i change something and reimport the item, i always get a new collection item in the object.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/87162916-b881-4f0d-aae9-f73145a0d981)

The question is, how can i identify the item and update the collection item instead of creating new one? I did not found any examples in the book or am i blind?
Thank you!

**Comment by BlackbitDevs** [comment]
> If i change something and reimport the item, i always get a new collection item in the object.

This is on purpose. When you want to keep some of the current field collection items while removing others, please enable `Truncate before import` checkbox and then use `$params['currentValue']` to loop through currently assigned field collection items. The ones which you want to keep you put into an array. And to this array you also add the ones which the import shall create. Then you return the array and have your desired items in the field collection.

**Comment by ascheider** [comment]
@BlackbitDevs Thanks for quick reply. CurrentValue seems not be present on this point.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/0193e0f9-8a4b-45c6-a61f-635b82c38229)
I guess i need to load the object here and extract the data via getter.

**Comment by BlackbitDevs** [comment]
No, it is present but currently there are no items in the field collection, that's why you get an empty array (= `[]`)

> I guess i need to load the object here and extract the data via getter.

When you have this thought on any place when you use Data Director, there most often is an easier way. The whole purpose of this bundle is to not have to learn about all those PHP and Pimcore internals.

**Comment by ascheider** [comment]
@BlackbitDevs you are right, the entities present in the currentValue. It works like you described.
