### ISSUE TITLE
Data director is creating lots of: No itemxpath given in config application log entries

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#119]
If you create a new data port in data director and do not configure it properly the data source type is "XML / HTML" preselected by default.
In this case data director writes a lot of application logger messages.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/3159c29b-c84a-41e9-a009-b5fbb000b461)
We had full disc at the weekend on one server, without doing import or another stuff with the profile.
The customer just created it for the later configuration.
The error is produced by data director in XmlParser class.
Maybe you can improve it and trigger this error, only if import with this data port is running, but not if the config is just not done yet.

**Comment by BlackbitDevs** [comment]
Do you have a call stack of the error? Imho this can only happen if the dataport was configured to be executed automatically (see checkbox `Automatically execute on new data`)

**Comment by ascheider** [comment]
@BlackbitDevs 
Here the profile no Mapping and never executed, only created:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/9daa6e40-e2fd-4bda-ab7a-f765193e02bc)
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/f00035db-78ae-4d3c-abb8-84193ca4f44d)
We have automatically execute on new data but on another data ports.
I made some stack traces on this point:

[stack_trace.txt](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/12607163/stack_trace.txt)

The first one is executed if you open up the data port where you have "XML / HTML" selected.

The second one is executed when you change object from another dataport which has 'Automatically execute on new data'.
Hope it helps.

**Comment by BlackbitDevs** [comment]
Have fixed this proble. Please update to latest 3.5.x-dev.
