### ISSUE TITLE
Could not infer value

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#122]
We try to use AI for getting data from OpenAI.

We have configured everything like in YouTube demonstration

When we run dataport we get such error:

`[ALERT] Could not infer value. Argument 3 passed to Blackbit\DataDirectorBundle\lib\Pim\Item\Importer::infer() must implement interface Pimcore\Model\Element\ElementInterface, null given, called in /var/www/pimcore.dev/www/vendor/blackbit/data-director/lib/Pim/Item/Importer.php on line 1629`

Is it a bug or we do something wrong.

Pim: 6.9
DD: 3.4.11

**Comment by betterapp** [comment]
OK. I have found. There was no Id (key mapping) for object

**Comment by BlackbitDevs** [comment]
Is fixed. actually the `infer` method code was already implemented to not need the `$dataObject` but the parameter was not allowed to be `null`. Have changed this now. As you say, it works now for you but if you need another 3.4.x release, just notify me.
