### ISSUE TITLE
Data Quality check does not work in Pim 6.9 ?

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#124]
I have set up small Product class I tried to check its data quality
I watched this tutorial:
https://www.youtube.com/watch?v=M1VVmpTjB_I

I have set up everything:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/68fd154f-2d93-427b-b81b-c24bf58f37c8)

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/2a695201-ba83-4edc-85a5-dcfc6409baa6)

And when I click on Save & Publish nothing happen.
The Product object is saved normally and data port is not running.

Why ?

PimCore: 6.9
DD: 3.4.11

**Comment by BlackbitDevs** [comment]
> The Product object is saved normally and data port is not running.

Because you have not checked the checkbox "Run automatically on new data" on the settings tab.
