### ISSUE TITLE
Compile error on custom fieldtypes

### ISSUE THREAD

**Issue by Alanin** [BlackbitDigitalCommerce/pimcore-data-director#131]
Hello,

we are going to make use of the fieldtypes with placeholders in several projects. but it seems that they are not compatible to pimcore 11 at the moment.

when saving the class with the new field we get that error
<img width="1252" alt="image" src="https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/1335755/040a3754-caac-4d7a-925e-027c67552dae">

we are on the latest 3.5.x-dev branch

thank you a lot for your work!
best regards
Jörg

**Comment by BlackbitDevs** [comment]
Fixed in 3.5.16:
<img width="543" alt="Bildschirmfoto 2023-11-23 um 18 21 31" src="https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/8749138/d0abbd0a-d177-44a2-9f06-065c463353da">
