### ISSUE TITLE
Request to update to dependency

### ISSUE THREAD

**Issue by Alanin** [BlackbitDigitalCommerce/pimcore-data-director#134]
Hello,

we are using DataDirector in a project where we need to connect to SAP using ODATA. Unfortunately the used oData Package is using "voku/portable-ascii": "2.*" and DataDirector is using "voku/portable-ascii": "1.*"

Would it be possible to update the dependency to version 2.* in composer.json?

Thank you a lot!
Best regards 
Jörg

**Comment by BlackbitDevs** [comment]
Have changed version constraint to `"voku/portable-ascii": "1.*|2.*` - DD uses only `ASCII::to_ascii()` and this stayed the same between versions 1 and 2.

**Comment by Alanin** [comment]
Thank you a lot!
