### ISSUE TITLE
null value for multihref in lib/Pim/Item/Importer.php

### ISSUE THREAD

**Issue by breakone** [BlackbitDigitalCommerce/pimcore-data-director#137]
I use the Version 3.5.16 and have a problem with the mapping of multihref fields.
In my case, the relation field is empty (null). In line 3890, the foreach breaks, because iteration over a null value is not possible:

```
foreach ($currentValue as $key => $currentAsset) {
...
```

There sould be a check before, if the "$currentValue" is null.

**Comment by BlackbitDevs** [comment]
Fixed in 3.5.29 - thanks for notifying.
