### ISSUE TITLE
Recursive call of findInTable(...)

### ISSUE THREAD

**Issue by breakone** [BlackbitDigitalCommerce/pimcore-data-director#142]
We run into problems in our deployment process.

The method `getDataports()` in the `AutomaticImportListener`

```
private static function getDataports() {
        if(self::$dataports === null) {
            self::$dataports = Dataport::getInstance()->find([], 'name');
        }

        return self::$dataports;
}
```

uses the `find(...)` method of the `PimcoreDbRepository`

```
public function find(array $where = [], string $order = null, int $count = null, int $offset = 0, $groupBy = null): array
{
        return $this->findInTable($this->getTableName(), $where, $order, $count, $offset, $groupBy);
}
```

And the `findInTable(...)` has a recursive call:

![findInTable](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/4848121/4010df31-1c81-4ce8-81ef-e07127beadbf)

So we run into a dead lock.

![grind](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/4848121/96273a61-c6f1-43e9-9721-2ced6d5b163d)

**Comment by BlackbitDevs** [comment]
Sorry for late response.
Does this problem still exist with latest 3.6 version?

**Comment by breakone** [comment]
@BlackbitDevs 
I really don't know because the customer set the project on hold.

**Comment by BlackbitDevs** [comment]
Closing this for now. Please add a comment if the problem reoccurs...
