### ISSUE TITLE
[BUG] Export document // Obsolete and removed function in use

### ISSUE THREAD

**Issue by FailXSiegen** [BlackbitDigitalCommerce/pimcore-data-director#143]
In all current versions including dev-master, 3.5.x-dev and 3.6.x-dev.

The issue:
If you are using the data director to export documents from objects an error occurs.

The lib/Pim/Item/Importer.php has an issue with removed functions since pimcore v 11
getContentMasterDocument() and setContentMasterDocument()
which are replaced with getContentMainDocument() and setContentMainDocument().

A simple str_replace from the functions did not help due to changes in the required set parameter object from the setContentMainDocument() function.

`Type error
Expected type 'Pimcore\Model\Element\ElementInterface'. Found 'Pimcore\Model\AbstractModel'. `

**Comment by BlackbitDevs** [comment]
Sorry for the late response. This is fixed in 3.6.52.

> A simple str_replace from the functions did not help due to changes in the required set parameter object from the setContentMainDocument() function.
> 
> Type error Expected type 'Pimcore\Model\Element\ElementInterface'. Found 'Pimcore\Model\AbstractModel'. 

Could you explain? Actually the parameter type has not changed:
Pimcore 10:
```php
/**
     * @param Document\PageSnippet|null $document
     *
     * @return $this
     */
    public function setContentMasterDocument($document)
```


Pimcore 11:
```php
public function setContentMainDocument(?PageSnippet $document): static
```

And in Data Director `setContentMainDocument($masterDocument)` gets only executed `if ($masterDocument instanceof PageSnippet) {`
