### ISSUE TITLE
Empty Video Datatype breaking Attribute Mapping

### ISSUE THREAD

**Issue by joFra210** [BlackbitDigitalCommerce/pimcore-data-director#146]
When trying to create a mapping for a Target Pimcore Dataobject with a Video Datatype there is an error preventing the display of the Attribute Mapping:

Typed property Pimcore\\Model\\DataObject\\Data\\Video::$type must not be accessed before initialization in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Data/Video.php:59\nStack trace:\n#0 /var/www/html/vendor/blackbit/data-director/lib/Pim/Serializer.php(810): Pimcore\\Model\\DataObject\\Data\\Video->getType()

To prevent this from happening you could just set the needed fields when creating the new Video Instance on the value check in the Serializer.php from line 804:

```php
            if (!$value instanceof Video) {
                $value = new Video();
                $value->setType("");
                $value->setData("");
            }
```

**Comment by BlackbitDevs** [comment]
Hi @joFra210 ,
which version of DD are you using? Because actually this has been fixed a long time ago in 3.2:
```php
if (!$value instanceof Video) {
    $value = new Video();
    $value->setType('asset');
    $value->setData(0);
}
```

**Comment by joFra210** [comment]
I am using version 3.5.38

**Comment by joFra210** [comment]
Perfect thank you!
