### ISSUE TITLE
Searching in preview

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#148]
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/dd742880-62cd-41b2-aa95-920c67515b8f)

This is something strange. I thought the data are wrong excluded but looks like search does not change backgroud color but insert html

**Comment by BlackbitDevs** [comment]
Fixed in 3.5.52 - actually this had been fixed since a long time in 3.6 but I forgot to backport it to 3.5. 
3.6 will be released within the next days...
