### ISSUE TITLE
NULL values for Image Galery type

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#149]
We have a **Product** class with **Images** field type Image Gallery.

We have also **Flyer** class which have Products field (Advanced m2m object relation).

I have set images to Product class.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/6136b032-6b93-463d-8f7f-254528397e60)

I see images in the Flyer object

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/0813caf8-752c-482f-8a36-5f1cebc566cc)

I created dataport which export flyer data with products data.
What I see is that in Images I have a array with null values. Why ?

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/d496b8c4-2da4-4188-bff8-44c6c63db84a)

**Comment by BlackbitDevs** [comment]
Which data query selector do you use?
For such cases I usually use `products:each:(images:each:(url))`
Maybe serializing Hotspotimage does not work correctly. I will try to reproduce your case soon...

**Comment by betterapp** [comment]
yes. I need it for 3.5 also. thank You

**Comment by BlackbitDevs** [comment]
Is also fixed in 3.5.54.
