### ISSUE TITLE
Automatic import for subfolder

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#15]
Hi
I have folder structure like this
![image](https://user-images.githubusercontent.com/7449124/155700409-91ecc809-e3e2-484f-a7de-e381f60deb84.png)

I want XML file be automatically imported if someone upload file to import folder

When I setup resource folder to something like this:
![image](https://user-images.githubusercontent.com/7449124/155700687-d374f4cd-8596-4c2c-b185-5bc770de88ec.png)

and upload xml file to any of root or subfolder it starting import.

But I tried to define that files will be imported only if they uploaded to import subfolder
I setup resource folder like this:
![image](https://user-images.githubusercontent.com/7449124/155701024-2f170fd7-d460-4f9f-a8f8-5c707411fe10.png)

But it is does not work.

Is it possible to do something like this with DD ?

**Comment by BlackbitNeueMedien** [comment]
I implemented glob expression support for version 2.8. But you have to add a `*` also add the end because `AutoImport/*/Import` will only find the directory, not the import files.
If it does not work, please give me a sign.
