### ISSUE TITLE
Get All languages values.

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#156]
We have a API that return products data.
We have some localization fields.
Is it possible to get values for all languages in one query ?

@BlackbitDevs

**Comment by BlackbitDevs** [comment]
Just for documentation if somebody else finds this issue:

From the Readme:

#### Get all languages for localized field

While you can request a specific language for example with the data query selector `name#en`, you can get the value of the field in all configured languages via `name#all`. This will give you

```json
{ "de": "Fahrrad", "en": "Bicycle" }
