### ISSUE TITLE
Attribute mapping not loading when video field in class

### ISSUE THREAD

**Issue by doubleBack00** [BlackbitDigitalCommerce/pimcore-data-director#157]
## Description
The attribute mapping in my dataport is not loading. As soon as I remove the video field in my class definition, it works.
Also tested it in other classes by adding a video field. Same problem there too.

## Excepted behaviour
Attribute mapping loads even if the class contains a video field.

## Screenshots
<img width="1054" alt="Screenshot 2024-04-23 at 15 06 57" src="https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/112825324/859ac1f9-97da-483a-9aea-0dfd8270c1eb">
<img width="293" alt="Screenshot 2024-04-23 at 15 07 14" src="https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/112825324/618eb1e6-2c92-4adb-af92-3a626743408f">

**Comment by BlackbitDevs** [comment]
Please have a look at #146.
Does the problem still exist after updating to a version >= 3.5.51 ?

**Comment by doubleBack00** [comment]
fixed in 3.6.16
