### ISSUE TITLE
Excel-Import - Data area

### ISSUE THREAD

**Issue by amogjackie** [BlackbitDigitalCommerce/pimcore-data-director#158]
If i want to Import data from an Excel-Sheet in Version 3.5.43 it works fine if i use for e.g. F:G in Settings->Data area in my Dataport. Since Version 3.5.54 id did not work anymore (also in 3.6) 
![Bildschirmfoto 2024-04-25 um 16 14 58](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/167509220/b31f7f76-5734-4745-87e8-4e4cecb5bf81)

I got this Error:
![Bildschirmfoto 2024-04-25 um 16 11 13](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/167509220/84d042e7-8011-46a1-9e48-6421473e1ad8)

If i use single col e.g "D" it works

**Comment by BlackbitDevs** [comment]
Fixed in 3.6.16.
Thanks for notifying.
