### ISSUE TITLE
Archive import files under different folders

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#16]
I have folder structure like this:

![image](https://user-images.githubusercontent.com/7449124/155701394-62bde6ab-36d6-46ad-8d4a-44f8e20b8260.png)

I want to run dataport when somone upload file to Import folder but want that after import the file will be moved
from Import to Imported folder.
For example if file is uploaded to 
/AutoImport/A/Import
it will be moved to /AutoImport/A/Imported after import
but
 if file is uploaded to 
/AutoImport/B/Import
it will be moved to /AutoImport/B/Imported after import

As I see I can specify one Archive folder path 

SO is it possible with DD ?

**Comment by betterapp** [comment]
I have done it under Result Callback Function.
After import I move imported file to other location.
This will not use Archive path but our own and it works.

**Comment by BlackbitNeueMedien** [comment]
Ok good, will nevertheless put this onto my To-do list as the goal of this bundle is to be able to solve most problem via configuration and only special cases by programming.
