### ISSUE TITLE
Call to a member function getFieldDefinitions() on null 

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#160]
I have exported and imported DataDirector definition
When I open the Attribute Mapping on imported definition I get:

`Error: Call to a member function getFieldDefinitions() on null in /vendor/blackbit/data-director/lib/Pim/Helper.php:544`

**Comment by betterapp** [comment]
I did not have ObjectBricks definition imported

**Comment by BlackbitDevs** [comment]
Have fixed this anyway ;-)
