### ISSUE TITLE
Error by Source-Type: 'Pimcore Grid Configuration'

### ISSUE THREAD

**Issue by sevarozh** [BlackbitDigitalCommerce/pimcore-data-director#161]
Pimcore 11.2.*
PHP 8.2.*
DataDirector 3.5.52

open Dataport and set 'Source data type' to 'Pimcore Grid Configuration':

`Status: 500 | 
URL: /admin/BlackbitDataDirector/importconfig/get-grid-configs?_dc=1714642574798
Method: GET
Message: Compile Error: Cannot declare class Pimcore\Bundle\SeoBundle\Model\Redirect\Listing, because the name is already in use`

Pimcore\Bundle\SeoBundle\Model\Redirect\Listing and other Pimcore classes that exist in pimcore/pimcore have the duplicates in the /blackbit/data-director/fallback folder, which is always autoloaded via composer.json

**Comment by BlackbitDevs** [comment]
> Pimcore\Bundle\SeoBundle\Model\Redirect\Listing and other Pimcore classes that exist in pimcore/pimcore have the duplicates in the /blackbit/data-director/fallback folder, which is always autoloaded via composer.json

No, this is not true. Only if the real class does not exist, it uses the classes from fallback folder, see https://getcomposer.org/doc/04-schema.md#psr-4
> If you want to have a fallback directory where any namespace will be looked for, you can use an empty prefix like:
{
    "autoload": {
        "psr-4": { "": "src/" }
    }
}

This is why you will see messages like 
> Warning: Ambiguous class resolution, "Pimcore\Bundle\SeoBundle\Model\Redirect\Listing" was found in both "<Pimcore root>/vendor/pimcore/pimcore/path/to/real/class" and "<Pimcore root>/vendor/blackbit/data-director/fallback/path/to/fallback/class", **the first will be used.**
when running `composer install` (or `update`).

Can you please post output of `composer install` or check `vendor/composer/autoload_classmap.php` which path gets used for `Pimcore\Bundle\SeoBundle\Model\Redirect\Listing`?

**Comment by sevarozh** [comment]
Hello, everything is ok in vendor/composer/autoload_classmap.php, so:
![Bildschirmfoto 2024-05-02 um 12 24 19](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/5694627/50f1bd47-8d19-4692-a8e1-a12a9535ff41)
But this error still happens when calling admin/BlackbitDataDirector/importconfig/get-grid-configs, directly when instantiating the listing:
![Bildschirmfoto 2024-05-02 um 12 41 36](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/5694627/34741810-49d1-4ec7-abd6-c02e0fd3ecdd)

Und wenn man diese Zeile mit try catch umwinkelt, kann man sehen dass die Klasse Pimcore\Model\GridConfig\Listing existiert einfach nicht mehr im Pimcore 11.  Pimcore\Model\GridConfig wurde in Admin Bundle verschoben 
https://github.com/pimcore/pimcore/issues/14605

Here it should be like this for PImcore 11:
`$configListing = new Pimcore\Bundle\AdminBundle\Model\GridConfig\Listing();`

Then everything works again. This problem does not occur in PImcore 10. 
For back compatibility with Pmcore < 11 you can simply check the class:
`
        if (class_exists(Pimcore\Model\GridConfig\Listing::class)) {
            $configListing = new Pimcore\Model\GridConfig\Listing();
        } else {
            $configListing = new Pimcore\Bundle\AdminBundle\Model\GridConfig\Listing();
        }
`

**Comment by BlackbitDevs** [comment]
Ah, thanks for suggested solution. Will apply it...

**Comment by BlackbitDevs** [comment]
Fixed in 3.6.19. Can you please try it, @sevarozh ?

**Comment by sevarozh** [comment]
yes perfect, now it works without errors
