### ISSUE TITLE
Importing into ClassificationStore Attributes

### ISSUE THREAD

**Issue by Alanin** [BlackbitDigitalCommerce/pimcore-data-director#162]
Hello,

it seems that the refactoring of the FieldMappings has broken the import into ClassificationStore Attributes.

In 3.6 and later in File lib/Pim/Item/FieldMapper/ClassificationStoreMapper.php in Line 108 '$this->map()' is called and therefore the method in the ClassificationStoreMapper is used which is not able to handle other fields than classificationStores.

In 3.5 the "central" map() method in lib/Pim/Item/Importer.php was called which was able to handle all kinds of fieldtypes.

Hope I was able to describe the issue and you can have a look into it.

thank you a lot and best regards
Jörg

**Comment by Alanin** [comment]
https://bitbucket.org/blackbitwerbung/pimcore-plugins-data-director/pull-requests/143

**Comment by BlackbitDevs** [comment]
You are right.
Thanks for your PR. Is fixed in 3.6.20
