### ISSUE TITLE
Unable to process item: TypeError: Blackbit\DataDirectorBundle\lib\Pim\Item\Importer::isPurged()

### ISSUE THREAD

**Issue by sevarozh** [BlackbitDigitalCommerce/pimcore-data-director#164]
Pimcore Version 10.6.9
DataDirector v3.5.42

blackbit/data-director/lib/Pim/Item/Importer.php(8264). Here map is called without $dataObject:

$parsedValue = $this->map($keyMapping, $keyValue, null, $def);

However, the map method checks whether the object is purged:
![Bildschirmfoto 2024-05-14 um 13 39 58](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/5694627/11181460-d323-4278-bdf1-79e443a71b4a)

Then the import is aborted with the exception: 
[INFO] --- Importing next raw data item
[ALERT] Unable to process item: TypeError: Blackbit\DataDirectorBundle\lib\Pim\Item\Importer::isPurged(): Argument #2 ($object) must be of type Pimcore\Model\AbstractModel, null given,

**Comment by BlackbitDevs** [comment]
Have fixed it in 3.6.28
Do you need a backport for 3.5?

The fix is in https://bitbucket.org/blackbitwerbung/pimcore-plugins-data-director/commits/4a6df3ad282387007f7be8174c8abbf5ea646974 (but in 3.5 the file structure is a bit different).

**Comment by sevarozh** [comment]
ok it's done, I corrected it in 3.5
Thanks
