### ISSUE TITLE
How can I check source file content for API query ?

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#169]
We have some API that update Product data.

How can see the body of the query. After run dataport file is removed from tmp directory.

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/4b4c0fa0-ceee-44d5-888b-b8e4f018b401)

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/383e2064-ce04-4aef-a009-1b688826f649)

**Comment by BlackbitDevs** [comment]
You can use import archive folder. 
Alternatively add `__source` as raw data field, this will provide a path to a temporary file which gets stored for 14 days (by default).

**Comment by betterapp** [comment]
thank You.
