### ISSUE TITLE
Compatibility with Pimcore Data Quality Management Bundle

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [BlackbitDigitalCommerce/pimcore-data-director#171]
Hi,

when using data director with the [Pimcore Data Quality Management Bundle](https://github.com/pimcore/data-quality-management-bundle) the visualization in the data object tree is not shown. Nevertheless, the visualization in the editor is shown properly.

This may be due to the changes made to the data object tree by the data director.

Thanks in advance. :)

/PIS

**Comment by BlackbitDevs** [comment]
Should be fixed in 3.6.42. Looking forward to your feedback.

**Comment by studio1gmbh-pimcore** [comment]
Thank you for the quick fix. It works just fine.

/PIS
