### ISSUE TITLE
Open Data Object by indexed field

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#172]
Hi

I have checked additional field as Indexed in class definition.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/2c83e32a-d9f6-4cbc-ab1a-7bd8d28fa76b)

But As I see it does not allow search by this field.
Wy ?

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/b7158972-13ea-4931-8cb3-a12ce50c6ac3)

**Comment by BlackbitDevs** [comment]
Currently only non-localized fields are supported. I add localized fields support in 3.7.

**Comment by betterapp** [comment]
when do you plan to officially release 3.7?

**Comment by BlackbitDevs** [comment]
Not far away. 3.7 will mostly enhance Pimcore's UX features:
1. [Tree tooltips](https://pimcore.com/docs/platform/Pimcore/Tools_and_Features/Custom_Icons)
2. Translatable element keys
3. Faster deletion of elements
4. [Path formatters](https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Class_Settings/Path_Formatter/) for better readability
5. Added field types
    - Calculated value fields
    - Text fields with placeholders
    - Button in object editing panel -> Efficient workflows
7. Back / Forward button to navigate in tabs
8. [Object preview](https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Class_Settings/Preview_Generator)
9. Open objects by key fields
10. [PIM perspective](https://pimcore.com/docs/platform/Pimcore/Tools_and_Features/Perspectives/)
11. Dashboard portlets

I hope to release 3.7 this month.
