### ISSUE TITLE
Problem after update from 3.2 -> 3.7

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#177]
Hi

I tried update DataDirector from 3.2 to 3.7
Pimcore: 6.9

After update when I open Pimcore admin I get messages:

![image](https://github.com/user-attachments/assets/91e3f5de-f5e5-4127-bdbb-ac515ac39a9f)

When I click on DataDirector icon I got error:

![image](https://github.com/user-attachments/assets/82ff8122-f295-4405-952a-6d3b08c6f5b0)

DataPort list is empty 
![image](https://github.com/user-attachments/assets/28fce0d7-3998-4687-83ac-3efc7b41a326)

**Comment by BlackbitDevs** [comment]
?? Please check the the database tables `plugin_pim_favorites` and `plugin_pim_importstatus` exist.

**Comment by BlackbitDevs** [comment]
Hmm, then something went wrong during installation. 
Please try `bin/console pimcore:bundle:install BlackbitDataDirectorBundle` but as those tables got created long time ago, I doubt that you will get the tables back.
Maybe check `pimcore_migrations` table to see which is the latest migration of DataDirector which got executed successfully.

To be honest, I would recommend to restore the database to the state before, check if the `plugin_pim_*` tables exist and then do the update again.

**Comment by betterapp** [comment]
fixed
