### ISSUE TITLE
SFTP Import issues

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#183]
I have issues with the SFTP Import
1.) If password contains # the function parse_url returns false and the import does not work

![image](https://github.com/user-attachments/assets/4c843792-3bca-4717-8cb0-b33a0f8b33a1)

You can execute it to reproduce the issue:
var_dump(parse_url('sftp://bla:56wefewf#EDC123456@host.com/sftp-bucket/file.xlsx'));

I replaced # with %23 in the password and replace it back after parsing, seems to fix the issue temporary:

![image](https://github.com/user-attachments/assets/ab2c6538-8817-4404-b284-a10f152040b8)

I can also of cource change the password, but DD needs here maybe better error handling if parsing fails.

2.) Read the full file works fine: sftp://bla:56wefewf#EDC123456@host.com/tk-sftp-bucket/TKPWebshop/PIM/mat_ext_K250_15.85.2655.xlsx but read the file with wildcard: sftp://bla:56wefewf#EDC123456@host.com/tk-sftp-bucket/TKPWebshop/PIM/mat_ext_K250_*.xlsx does not work i get the "Could not find an import resource for" error.

![image](https://github.com/user-attachments/assets/04157d34-9c3e-40af-b6e3-ab1b360d28d1)

3.) Question about archive. 
After import of the FTP file, i want to move it to the archive directory on the server. As i can see it is not supported? Because archive folder in the dataport always creates the folder locally in the assets. I can also not see any result callback or document functions which can move the file on the server after the import.

Thank you!

**Comment by BlackbitDevs** [comment]
Which Data Director version are you using? I have adjusted implementation of FTP url parsing for support of special characters in password in 3.7:
```php
$urlParts = parse_url($this->source);
if($urlParts === false && preg_match('/^sftp:\/\/(.+):(.+)@/', $this->source, $match)) {
    $source = str_replace($match[0], 'sftp://', $this->source);
    $urlParts = parse_url($source);
    $urlParts['user'] = $match[1];
    $urlParts['pass'] = $match[2];
}
```

Can also backport this to 3.6 if you prefer.

> sftp://bla:56wefewf#[EDC123456@host.com](mailto:EDC123456@host.com)/tk-sftp-bucket/TKPWebshop/PIM/mat_ext_K250_*.xlsx does not work i get the "Could not find an import resource for" error.

Wildcards in SFTP urls are only supported in 3.7 and above.

> After import of the FTP file, i want to move it to the archive directory on the server.

The import archive functionality only supports Pimcore asset folders and file system folders, currently not remote folders. 2 options:
1. Use special field `__file` in your raw data fields. This will contain the path to a temporary file for the currently processed file from SFTP. Collect the used files in `$params['transfer']->importFiles`. In result document action adapt the template function for "Upload via SFTP" to upload the file to the desired folder on SFTP.
2. Contact info@blackbit.de to get support for SFTP folders as archive folder.
