### ISSUE TITLE
how to change the Filesystem adapter to pimcore asset in result document action after s3 import 

### ISSUE THREAD

**Issue by cg15** [BlackbitDigitalCommerce/pimcore-data-director#186]
**when I import using s3 url, I need to use save as asset in the result document action.the code like this**
```              
$folder = \Pimcore\Model\Asset\Service::createFolderByPath({{ Response Document Asset Target Path }} ?: '/' );
$asset = \Pimcore\Model\Asset::getByPath($folder->getFullPath().'/'.$filename);
if($asset === null) {
    $asset = \Pimcore\Model\Asset::create($folder->getId(), array(
        'filename' => $filename,
        'stream' => $params['response']->getOutputStream()
    ));
} else {
    $asset->setStream($params['response']->getOutputStream());
    $asset->save();
}

return 'Successfully saved export document to '.$asset->getFullPath();
```
**but have a error**
```
Next League\Flysystem\UnableToCheckFileExistence: Unable to check file existence for: /product/20241030143541.csv in /var/www/html/vendor/league/flysystem/src/UnableToCheckFileExistence.php:14
Stack trace:
#0 /var/www/html/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(129): League\Flysystem\UnableToCheckFileExistence::forLocation('ap/product/sys-...', Object(Aws\Exception\CredentialsException))
#1 /var/www/html/vendor/league/flysystem/src/Filesystem.php(36): League\Flysystem\AwsS3V3\AwsS3V3Adapter->fileExists('ap/product/sys-...')
#2 /var/www/html/vendor/pimcore/pimcore/models/Asset.php(751): League\Flysystem\Filesystem->fileExists('/ap/product/sys...')
```
`#0 /var/www/html/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(129): ` **seems that the s3 directory is used as the export directory, but I want to export it to the pimcore asset directory.**

**Comment by BlackbitDevs** [comment]
If the goal is to import assets from S3, you can specify "Source data type: File system", "target class" is `Asset`, in "Import source" you enter the S3 url. Raw data field is `file` and maybe the file name `basename $file` (raw data field name: file name). And in attribute mapping you map raw data field "file name" to `Object Name`, enable this as key field in transformation options. And map "file" to `Stream`.

No need to use result callback function template "Save as asset" for this use-case.
