### ISSUE TITLE
Very slow import 

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#187]
Why complex dataports running so slow.
We have dataport that should import about 35k products with some attributes, bricks data and so on.

![image](https://github.com/user-attachments/assets/2abe329c-fe98-43fa-96d4-bc400aed3787)

**Comment by betterapp** [comment]
How is it possible that canceled dataport show time progress - it is running or what ?

https://github.com/user-attachments/assets/f7554d0d-b2d0-4bc8-a603-6160fc55b373

**Comment by betterapp** [comment]
![image](https://github.com/user-attachments/assets/69ab4e2d-8d02-4b42-9073-21c87ca6d568)

Terrible slow.

**Comment by betterapp** [comment]
@BlackbitDevs 

I checked log and see something strange.

./php.log:[2024-11-08T09:44:38.997926+01:00] pimcore.ERROR: could not resolve field "DriveTrains~BackGearType" in class Product [] []
./php.log:[2024-11-08T09:44:42.292088+01:00] pimcore.ERROR: could not resolve field "ListPrice1" in class Product [] []
./php.log:[2024-11-08T09:44:42.292161+01:00] pimcore.ERROR: could not resolve field "ListPrice2" in class Product [] []
./php.log:[2024-11-08T09:44:42.292188+01:00] pimcore.ERROR: could not resolve field "ListPrice3" in class Product [] []

1. We do not have such fields in class: ListPrice1, ListPrice2, ListPrice3, DriveTrains~BackGearType
![image](https://github.com/user-attachments/assets/9c9f16e1-6437-4d90-8179-c570f97b42f7)
![image](https://github.com/user-attachments/assets/4d580c67-a60b-4668-828e-8bf36bdd5fc1)


2. DriveTrains~BackGearType - why this name have ~ ??

Our settings:
![image](https://github.com/user-attachments/assets/cdcd9c4e-da94-406a-96b5-ad6a96a019cb)

Our mapping:
![image](https://github.com/user-attachments/assets/1b2ee853-5c0c-4373-81f1-345a13f09a62)


So question is why DataDirector try to do anything with those not existed fields ?

**Comment by betterapp** [comment]
Another problem

@BlackbitDevs 

This request:
![image](https://github.com/user-attachments/assets/bb23a426-7417-42ee-9062-22e2153846df)

With such payload:
![image](https://github.com/user-attachments/assets/a7fea9ae-1100-441d-8883-fdce418a3960)

Took almost 20 seconds:

![image](https://github.com/user-attachments/assets/d73f2311-121d-42b3-aa28-95222880b400)

**Comment by BlackbitDevs** [comment]
What response are you expecting here? You have put a lot of problems into one issue without any dataport details.
Please check if the problem still exists on latest 3.7 version - if yes, then we can analyse this with a support call or access to your system. Please write to help@blackbit.com if you are interested.

**Comment by betterapp** [comment]
@BlackbitDevs 

Lets focus on one problem then.
Removing field's assigment with (X).

![image](https://github.com/user-attachments/assets/bfc93bac-f9fc-4e18-b2ab-e65d2a1050e7)

We have  aproduct class with more then 100 fields + we have about 30 bricks used by the product class.
Every brick have about 5-15 fields.

Attribute mapping for the dataport which use Product class take 20 second.

As I see everytime when I remove assigment DataDirector reload attribute mapping definition and return it to Ext.JS.

Problematic is this loop:

```
Dataport::clearImportHashes($dataportId);
Dataport::clearResultCache($dataportId);
foreach($returnMappings as $returnMapping) {
    $config['mapping'][] = $returnMapping();
}
```
in file: `vendor/blackbit/data-director/Controller/MappingconfigController.php`

Do we really need reload whole mapping definition here ? Maybe can just update specific row on grid ?
