### ISSUE TITLE
Status of the import on callback function

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#19]
![image](https://user-images.githubusercontent.com/7449124/156123321-c95fda45-b13a-476a-b9c3-bf7bf84e4d82.png)

I can check that import finished with **`$params['lastCall'] == true`** but do not see param for import status.
Can not see it in the code under
`//lib/Pim/Item/Importmanager.php:384`

**Comment by betterapp** [comment]
I think $params should include all data from

**`plugin_pim_importstatus`** table

they are very useful and could be used to manage many things under result callback function.

What do You think ? Is it possible to add it or we need to create patch ?

**Comment by BlackbitNeueMedien** [comment]
Of course this is possible. For what use-case do you exactly need which fields from `plugin_pim_importstatus` table?
"Import status" is a difficult thing because in the database table you will only see something like finished but this does not tell you if there were any problems durign the dataport run. For this you can use `$params['logs']` which contains an array grouped by error severity like 
```php
[
  'warning' => ['First error', 'Second error'],
  'notice' => ['First notice', 'Second notice']
]
```
For example you could have a check like 
```php
if($params['lastCall'] && empty($params['logs']['warning']) && empty($params['logs']['alert']) && empty($params['logs']['emergency'])) {
  // import was successful
}
```

**Comment by betterapp** [comment]
We need to generate separate log file per Supplier.
Every supplier will import their own file using the same dataport.
I want to create this log file under result callback function after `lastCall` and save under Supplier's log folder.

But

I know that I am able to get logs data only for every item so in lastCall I will have only log data for last record.
There is no logs for all records in $params which I could use with lastCall variable.

I could use logs for items but I do not have static ID (aka KEY from plugin_pim_importstatus table) which I could use to separate logs for example two Suppliers.

**Comment by BlackbitNeueMedien** [comment]
> I know that I am able to get logs data only for every item so in lastCall I will have only log data for last record.
Right, I missed that.
But you can either write this data for every item into `$params['transfer']->logs` or directly into the target log file. And what do you need the import status key for? You can just create your own id and put it into $params['transfer']->runId. For example you could put
```php
if(!isset($params['transfer']->runId)) {
  $params['transfer']->runId = uniqid();
}
// here $params['transfer']->runId will always be the same for all raw data items
```

**Comment by betterapp** [comment]
I missed that `$params['transfer']` allow to share data between every items. I saw in code that you use `eval()` for run callback function for every item - but did not analyze the code if there is something that can share data between every `eval()` call.
 
In this case I do not need static ID - I can use `uniqid()`. I will check it.
Thanks

BTW:
As I know in `$params['logs']` there is also `info` key - right ?
So maybe You could add this information to documentation that `$params['logs']` can have:

[
```
  'info' => ['First info', 'Second Info'],
  'warning' => ['First error', 'Second error'],
  'notice' => ['First notice', 'Second notice']
]
```

**Comment by BlackbitNeueMedien** [comment]
Added the `logs` array structure to the docs.

**Comment by betterapp** [comment]
Thanks. I appreciate it.
