### ISSUE TITLE
Classification Store - Localization - $params['currentValue'] and $params['currentObjectData'] contain only english language

### ISSUE THREAD

**Issue by cmann90** [BlackbitDigitalCommerce/pimcore-data-director#199]
**Environment**
Pimcore: v11.4.1
Platform version: v2024.3
Data director: 3.7.66

**Attachments**
[bug - data director.zip](https://github.com/user-attachments/files/18078961/bug.-.data.director.zip)
![image](https://github.com/user-attachments/assets/5596fc6b-bccd-419a-86eb-8559dc6e7ad3)

**Issue**
**$params['currentValue']** and **$params['currentObjectData']** contain only english data.

Class overview
![image](https://github.com/user-attachments/assets/a2786662-1850-46a0-ab58-4455040774b3)

Product example with 3 languages
![image](https://github.com/user-attachments/assets/36b08849-edf0-4a02-b437-2e5b995740f0)

Data Director configuration (Also missing "Example data" in the "Raw Data Fields" section)
![image](https://github.com/user-attachments/assets/fec367d0-5d41-42d9-8ccb-ec053af69d0b)

Example import file
```xml
<tests language="en">
    <test>
      <identifier>testProduct</identifier>
      <myInput>xmlInput</myInput>
      <myTextarea>xmlTextarea</myTextarea>
      <myWYSIWYG>xmlWYSIWYG</myWYSIWYG>
    </test>
</tests>
```

Issue **$params['currentValue']** with collection type
![image](https://github.com/user-attachments/assets/4d02a747-7eff-4a7c-9d1f-e6bf76b8f900)

Issue **$params['currentObjectData']** with collection type
![image](https://github.com/user-attachments/assets/a78e803a-bdd7-466f-84a4-69c2ce5be99b)

Issue **$params['currentValue']** with collection specified group, key and german language
![image](https://github.com/user-attachments/assets/fc437bd9-e66f-44a8-9ce5-80472154c45d)

**Comment by BlackbitDevs** [comment]
This is not a bug, it was simply not supported yet ;-)

But in 3.7.69 this is available, example output:
```json
{
  "classificationStore": {
    "test": "en", // this is the value of field "test" in the current language of the export
    "test#en": "en", // this is new
    "test#de": "de", // this is new
    "test#fr": null // this is new
  }
}
```

**Comment by cmann90** [comment]
Thanks a lot for the fast implementation! 
Works mostly pretty good.

**Two things came up during testing:**
1.  "test" should show the classification store "default" instead of the default language set in the system settings because it is possible to set this value but this way it is not possible to read it. 
Or maybe have an additional "default" language?
![image](https://github.com/user-attachments/assets/f4f6f660-3d5a-4b2d-8998-ee5cb91427a2)
![image](https://github.com/user-attachments/assets/da123907-efd8-47ea-bf95-4600b712b9b9)


2. The summary diff will only show changes for the default(en) language and ignore all other languages (Changes are still applied correctly)
![image](https://github.com/user-attachments/assets/dbd7bfeb-91d9-4514-b399-dd3bbc7f38b1)

**Comment by BlackbitDevs** [comment]
@cmann90 Have added the `default` language in 3.7.71:
```json
{
  "classificationStore": {
    "test": "en", // this is the value of field "test" in the current language of the export, here this was English
    "test#default": "default", // this is new
    "test#en": "en", // this is new
    "test#de": "de", // this is new
    "test#fr": null // this is new
  }
}
```

I have implemented it this way to be consistent with other localized field: The localized field name without language suffix contains the value from the language which the export got started with. Imho, the `default` language for classification store fields does not make sense anyway - but, Pimcore has it and so DD needs to be able to extract it.
