### ISSUE TITLE
Problem with big XSL file.

### ISSUE THREAD

**Issue by danielczestki** [BlackbitDigitalCommerce/pimcore-data-director#2]
We have XLS file with 10000 rows and about 75 cols.
When I click on Attribute mapping it show loading progress bar for few seconds
and then I see such error.

![image](https://user-images.githubusercontent.com/2109480/146430877-5aa66a3e-bee7-4fc4-a2b9-afc35869f746.png)

Is there a limit for max. rows Data Director can handle ?

**Comment by BlackbitNeueMedien** [comment]
Which version do you use?
Actually there is no limit. For the attribute mapping there are 2 main things which are done:
- get raw data to be used for preview
- get data object of target class for preview which matches the key field(s) of the selected raw data item

The first step gets skipped when you already have raw data for this dataport available. SO pleas go to `History & Run import` panel and start the raw data import.

**Comment by danielczestki** [comment]
We use 2.5 version. We use PimCore 6.9.6.

So we should firstly run raw import without mapping anything ?

**Comment by BlackbitNeueMedien** [comment]
Yes, raw import does only mean to extract the configured raw data fields from the import resource to a flat table. There is no mapping involved. Only in the second step of an import (raw data processing) the extracted raw data is used to create / update Pimcore elements - and for this of course the mapping is necessary.

**Comment by danielczestki** [comment]
Version >= 2.6  does not work with Pimcore <10

**Comment by BlackbitNeueMedien** [comment]
Actually it does. But why don't you update to 2.7 directly? This is the current stable version. And this works for sure with Pimcore 6.
Which error do you get?

**Comment by danielczestki** [comment]
First a create fresh copy of pimcore 6.9

composer require pimcore/pimcore:^6.9

then I try to require blackbit data director.

Composer errors:

- Can only install one of: phpseclib/phpseclib[3.0.12, 2.0.8].
    - Can only install one of: phpseclib/phpseclib[2.0.8, 3.0.12].
    - Can only install one of: phpseclib/phpseclib[2.0.8, 3.0.12].
    - Conclusion: install phpseclib/phpseclib 2.0.8
    - Installation request for phpseclib/phpseclib (locked at 3.0.12) -> satisfiable by phpseclib/phpseclib[3.0.12].

**Comment by denniskorbginski** [comment]
Hi! Could you try running the require command with the `-W` flag, as in `composer req blackbit/data-director -W`? This should allow composer to downgrade phpseclib to a compatible version. I just tested these steps with a fresh pimcore 6.9.6 installed from the [pimcore/skeleton](https://github.com/pimcore/skeleton) project.

**Comment by danielczestki** [comment]
[Symfony\Component\Console\Exception\RuntimeException]  
  The "-W" option does not exist.  
  
  hahaha wth

**Comment by denniskorbginski** [comment]
Right, the `-W` shorthand was added in composer 2. In composer 1, you can use `--update-with-all-dependencies` instead. Sorry for that. 😅

**Comment by danielczestki** [comment]
Yes I see. :P

**Comment by denniskorbginski** [comment]
Alternatively, you could also manually downgrade phpseclib by requiring version 2 explicitly, like `composer req phpseclib/phpseclib:^2`.

Just for context: Pimcore ships with phpseclib 3 by default. The data director requires the [flysystem](https://github.com/thephpleague/flysystem) package, which in turn requires phpseclib v2. Sorry for the problems this causes.

**Comment by danielczestki** [comment]
Problem 1
    - Conclusion: don't install symfony/http-client v5.3.10
    - Conclusion: don't install symfony/http-client v5.3.8
    - Conclusion: don't install symfony/http-client v5.3.7
    - Conclusion: don't install symfony/http-client v5.3.4
    - Conclusion: don't install symfony/http-client v5.3.3
    - Conclusion: don't install symfony/http-client v5.3.2
    - Conclusion: don't install symfony/http-client v5.3.0
    - Conclusion: don't install symfony/http-client v5.2.12
    - Conclusion: don't install symfony/http-client v5.2.11
    - Conclusion: don't install symfony/http-client v5.2.10
    - Conclusion: don't install symfony/http-client v5.2.9
    - Conclusion: don't install symfony/http-client v5.2.8
    - Conclusion: don't install symfony/http-client v5.2.7
    - Conclusion: don't install symfony/http-client v5.2.6
    - Conclusion: don't install symfony/http-client v5.2.4
    - Conclusion: don't install symfony/http-client v5.2.3
    - Conclusion: don't install symfony/http-client v5.2.2
    - Conclusion: don't install symfony/http-client v5.2.1
    - Conclusion: don't install symfony/http-client v5.2.0
    - Conclusion: don't install symfony/http-client v5.1.11
    - Conclusion: don't install symfony/http-client v5.1.10
    - Conclusion: don't install symfony/http-client v5.1.9
    - Conclusion: don't install symfony/http-client v5.1.8
    - Conclusion: don't install symfony/http-client v5.1.7
    - Conclusion: don't install symfony/http-client v5.1.6
    - Conclusion: don't install symfony/http-client v5.1.5
    - Conclusion: don't install symfony/http-client v5.1.4
    - Conclusion: don't install symfony/http-client v5.1.3
    - Conclusion: don't install symfony/http-client v5.1.2
    - Conclusion: don't install symfony/http-client v5.1.1
    - Conclusion: don't install symfony/http-client v5.1.0
    - Conclusion: don't install symfony/http-client v5.0.11
    - Conclusion: don't install symfony/http-client v5.0.10
    - Conclusion: don't install symfony/http-client v5.0.9
    - Conclusion: don't install symfony/http-client v5.0.8
    - Conclusion: don't install pimcore/output-data-config-toolkit-bundle v4.0.2
    - Conclusion: don't install symfony/http-client v4.4.8
    - Conclusion: remove pimcore/output-data-config-toolkit-bundle v4.0.2
    - Conclusion: don't install symfony/http-client v4.4.7|don't install pimcore/output-data-config-toolkit-bundle v4.0.2
    - Installation request for symfony/deprecation-contracts (locked at v2.4.0) -> satisfiable by symfony/contracts[v2.4.0], symfony/deprecation-contracts[v2.4.0].
    - Conclusion: don't install pimcore/output-data-config-toolkit-bundle v4.0.2|don't install pimcore/pimcore v6.9.6|install symfony/http-client v4.4.7|install symfony/http-client v4.4.8
    - Conclusion: don't install pimcore/pimcore v6.9.6
    - Conclusion: don't install symfony/symfony v5.3.11|remove pimcore/pimcore v6.9.6|install symfony/symfony v3.4.43|install symfony/symfony v4.4.11
    - Conclusion: don't install symfony/symfony v5.3.12|remove pimcore/pimcore v6.9.6|install symfony/symfony v3.4.43|install symfony/symfony v4.4.11
    - Conclusion: don't install symfony/symfony v5.3.9|remove pimcore/pimcore v6.9.6|install symfony/symfony v3.4.43|install symfony/symfony v4.4.11
    - Conclusion: don't install symfony/symfony v5.3.10|remove pimcore/pimcore v6.9.6|install symfony/symfony v3.4.43|install symfony/symfony v4.4.11
    - doctrine/dbal 2.13.0 conflicts with pimcore/pimcore[v6.9.6].
    - doctrine/dbal 2.13.1 conflicts with pimcore/pimcore[v6.9.6].
    - doctrine/dbal 2.13.2 conflicts with pimcore/pimcore[v6.9.6].
    - doctrine/dbal 2.13.3 conflicts with pimcore/pimcore[v6.9.6].
    - doctrine/dbal 2.13.4 conflicts with pimcore/pimcore[v6.9.6].
    - doctrine/dbal 2.13.5 conflicts with pimcore/pimcore[v6.9.6].
    - doctrine/dbal 2.13.6 conflicts with pimcore/pimcore[v6.9.6].
    - laminas/laminas-code 4.4.0 conflicts with pimcore/pimcore[v6.9.6].
    - laminas/laminas-code 4.4.1 conflicts with pimcore/pimcore[v6.9.6].
    - laminas/laminas-code 4.4.2 conflicts with pimcore/pimcore[v6.9.6].
    - laminas/laminas-code 4.4.3 conflicts with pimcore/pimcore[v6.9.6].
    - laminas/laminas-code 4.5.0 conflicts with pimcore/pimcore[v6.9.6].
    - laminas/laminas-code 4.5.1 conflicts with pimcore/pimcore[v6.9.6].
    - symfony/symfony v3.4.43 conflicts with pimcore/pimcore[v6.9.6].
    - symfony/symfony v4.4.11 conflicts with pimcore/pimcore[v6.9.6].

**Comment by danielczestki** [comment]
looks like we use something that blocking use this version

**Comment by danielczestki** [comment]
but You are right. on fresh PimCore 6.9 I can install it.

**Comment by betterapp** [comment]
working. can be closed.

**Comment by betterapp** [comment]
We have the same problem again but on Save dataport action.
The XLSX file have about 85k rows and about 75 columns.

**Comment by BlackbitNeueMedien** [comment]
On saving dataport, there is actually nothing done with the import resource. Only after saving the dataport settings get reloaded and there is a request to `get-demo-data`. Could you check in the network panel of your browser's debug toolbar which request causes the error?

**Comment by danielczestki** [comment]
Why when I divide the file into smaller parts it is ok ?
![obraz](https://user-images.githubusercontent.com/2109480/162185157-dd7b5622-73b6-489a-98d1-e569b966392c.png)

**Comment by danielczestki** [comment]
there is nothing in the log

**Comment by BlackbitNeueMedien** [comment]
Hmm ok. will have a look at those places. Both need example data and they get it from the import resource file. Will need to look if it is possible to stream Excel files.

**Comment by BlackbitNeueMedien** [comment]
Ah, it seems that [Spout](https://opensource.box.com/spout/) can stream-read Excel files. I would put this to my todo list unless you say that it has high priority for you, then we would send you an offer to implement this as soon as possible.

**Comment by danielczestki** [comment]
We use DD 2.8.2.
But I remember that we could use big file without problem - maybe it was 2.8.0 ?
Now I do not remember.

Has there been any changes in this matter recently ?

**Comment by BlackbitNeueMedien** [comment]
No, the `ExcelParser` has not been touched recently (and it currently uses `phpoffice/phpspreadsheet` which loads the Excel file completely into memory). 
Perhaps you can try with `3.0.x-dev` on a development system.
