### ISSUE TITLE
ERROR: Could not load preview panel grid's columns

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#21]
Hi.

We want to setup export data for PimCore object - class Product.
Our definition is very complex - have many different relations to other objects and bricks.

When we click `Auto Create` button under `Row Data Field` section it generate almost 1000 rows.
Now when we want to Save dataport we got error:

![image](https://user-images.githubusercontent.com/7449124/156720656-43bb4904-d667-4883-9093-82d0b90b71ce.png)

And the Attribute mapping panel is empty:
![image](https://user-images.githubusercontent.com/7449124/156720758-d3b3ed60-e81a-4c45-beb1-44539313a7d7.png)

The problem is here:
![image](https://user-images.githubusercontent.com/7449124/156720838-7c760518-79c7-443b-bc82-5d168c07fda5.png)

I tried to debug  a little why the error occurred:
![image](https://user-images.githubusercontent.com/7449124/156720920-dced0f24-023f-4ecd-89b7-c6aa1ccba672.png)

and saw something like this:
![image](https://user-images.githubusercontent.com/7449124/156721014-3259c844-a3f3-412e-8958-1b194f134bdb.png)

What can we do about it ?
Is it a bug or DD can not handle so much complex class definition ?

**Comment by BlackbitNeueMedien** [comment]
Can you export the dataport configuration and upload it somewhere where I can access it? 
Or at least the class definition so that I can try to reproduce the problem?

**Comment by betterapp** [comment]
Yes I can but I can not share it publicly. Can You give me your email address @BlackbitNeueMedien ??

**Comment by BlackbitNeueMedien** [comment]
Please send it to hilfe@blackbit.de or info@blackbit.de together with a link to this issue.

**Comment by betterapp** [comment]
OK. Email sent to [hilfe@blackbit.de](mailto:hilfe@blackbit.de)

**Comment by betterapp** [comment]
@BlackbitNeueMedien I got email with information that this issue can be fixed but we need to pay for it. Is it true or You will try to reproduce the problem ?

**Comment by betterapp** [comment]
@BlackbitNeueMedien 

The problem exist also on small class with only few fields.
I have a class SmallProduct with 3 filelds only.
And have the same behavior. Attribute Mapping is empty.

Class definition:
![image](https://user-images.githubusercontent.com/7449124/157425996-5ff36fe9-8fb0-4580-979c-1932bbfe4aa1.png)
 
DD export definition
Settings: 
![image](https://user-images.githubusercontent.com/7449124/157426189-58f42f49-efe8-4341-9aac-1b9cc520ef47.png)

Attribute mapping:
![image](https://user-images.githubusercontent.com/7449124/157426311-7a9b4eb0-f337-474d-945e-f82930d406a1.png)

When I click here:
![image](https://user-images.githubusercontent.com/7449124/157426486-6c821c72-1347-44da-aecb-22bf7fe29899.png)

I got error message:
![image](https://user-images.githubusercontent.com/7449124/157426445-7b3f4078-9638-482c-9cd9-5ed817923a30.png)

Here is the class definition and DD dataport definition (changed .json to .txt extension):

[class_SmallProduct_export.txt](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/8213928/class_SmallProduct_export.txt)
[bb-export-small-product.txt](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/8213929/bb-export-small-product.txt)

**Comment by betterapp** [comment]
I found out that when I create new class definition from ground - everything is ok.
When I create new class and import this definition to it - it is not working.

Is DD cache some data ?

**Comment by betterapp** [comment]
Debug for not working class:

`$targetConfig['itemClass'] `value is "0" in 
`\Blackbit\DataDirectorBundle\lib\Pim\targetConfig`

This should have Source Data Class id.

**Comment by betterapp** [comment]
Hmm. But now it does not work even for new class.
There is a big bug :)

**Comment by betterapp** [comment]
https://vimeo.com/manage/videos/686271892/6875370ccc

**Comment by betterapp** [comment]
@BlackbitNeueMedien 

https://www.youtube.com/watch?v=0vTrCR2qjYk

**Comment by betterapp** [comment]
The problem is that plugin_pim_fieldmapping table have no data for dataport.
I checked that the data are created with:
`\Blackbit\DataDirectorBundle\model\Fieldmapping::create` method
which is called from two locations:
\Blackbit\DataDirectorBundle\Controller\ImportconfigController::importDataport
\Blackbit\DataDirectorBundle\Controller\MappingconfigController::saveConfigAction

The second should run for `@Route("/save-config")` but it is never used ??

@BlackbitNeueMedien  when it iwll be fixed. We can not use Your bundle for exporting data.

**Comment by BlackbitNeueMedien** [comment]
> @BlackbitNeueMedien
> 
> https://www.youtube.com/watch?v=0vTrCR2qjYk

Hi @betterapp ,
this is not how exports work. You created the raw data fields but did not tell the data director what to do with this raw data. Please select a template in the `Result callback function`, e.g. Export raw data as JSON. This function will contain virtual fields like `{{ firstName }}`. Those will automatically appear in attribute mapping then and get mapped to the raw data fields with the same name. Of course you can remap them to another field or add a callback function - the same as you can do for imports.
Please have a look at the [tutorial video about exports](https://www.youtube.com/watch?v=bsBY9hVeKcY&list=PL4-QRNfdsdKIfzQIP-c9hRruXf0r48fjt&t=1120s ) - here it is explained how to define the export format. At the time of recording there were no virtual fields yet so all raw data fields got exported but essentially it works the same. Perhaps you even see it better in the [grid export tutorial video](https://www.youtube.com/watch?v=1zFlAa6AXjE&list=PL4-QRNfdsdKIfzQIP-c9hRruXf0r48fjt&t=170s) - there virtual fields do get used.

**Comment by betterapp** [comment]
@BlackbitNeueMedien You are right. Sorry.
