### ISSUE TITLE
Delete many fields from Raw Data Field Setting

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#22]
I have selected many fields and tried to remove them all with one delete click.
But DD remove only the one field where I click right mouse button.
Is it possible to add functionality for remove all selected fields ?

Currently I remove those fields direct in database: plugin_pim_rawitemFIeld

![image](https://user-images.githubusercontent.com/7449124/158787022-feba7cd0-1d93-4aaa-8cec-04a5856e6f42.png)

**Comment by BlackbitNeueMedien** [comment]
Oh, this is a bug. This should work - as moving multiple fields via drag & drop is also possible. Will fix it in the evening...

**Comment by BlackbitNeueMedien** [comment]
Fixed in 2.8.2. It already worked with the "Delete" button but it did not with the context menu option.
