### ISSUE TITLE
cannot access block element with data query selector "all"

### ISSUE THREAD

**Issue by djdgtls** [BlackbitDigitalCommerce/pimcore-data-director#23]
I have a block element in a data object class that needs to be read by a data query selector:
![image](https://user-images.githubusercontent.com/36883363/158817224-150e1397-46d5-4cb4-8403-aaa4d41e711c.png)
I tried the documented ways to access the element, but the "all" selector does not work as expected:
![image](https://user-images.githubusercontent.com/36883363/158825057-6cd39d2d-1b72-4d8d-9417-b26194a3bb9d.png)

**Comment by BlackbitNeueMedien** [comment]
You are right, this is currently not possible for `block` fields. If possible, perhaps you can use a `field collection`. 
I have added this bug to my todo list. If you want to prioritize fixing this bug, please write an email to hilfe@blackbit.de.
