### ISSUE TITLE
Problem with wildcards under Path to Excel File

### ISSUE THREAD

**Issue by danielczestki** [BlackbitDigitalCommerce/pimcore-data-director#24]
I have a DataPort that configuration is:
![obraz](https://user-images.githubusercontent.com/2109480/162379282-2505ea86-3ba9-40fe-8e22-2cf4685bb2a6.png)

When I setup 
`Path to Excel File: /Files/*/ProductImport/*.xlsx`
And put export.xlsx file under
`/Files/Daniel/ProductImport/`  folder,  DD do not start automaticly import. Option to do this is enabled.

But when I use XML file it is working ok.
Why ?

We use DD: 2.8.2

**Comment by BlackbitNeueMedien** [comment]
Is `/Files` a Pimcore asset folder or a filesystem folder? For the latter we currently cannot detect changes, so automatic imports will not work. For Pimcore asset folders the logic for XML and Excel dataports is actually the same.

**Comment by danielczestki** [comment]
Yes it is a PimCore asset folder.

**Comment by danielczestki** [comment]
up !

**Comment by danielczestki** [comment]
So for Filesystem folder autoimport XLSX fiel does not work.
and
for Asset folders autoimport XLSX should work - right - but it is not.

When it will be fixed ?

**Comment by BlackbitNeueMedien** [comment]
Fixed in 2.8.5. Automatic imports with Excel did not work at all - independent of wildcards are if the import resource was a Pimcore asset or filesystem folder.

**Comment by danielczestki** [comment]
Working! Thanks!
