### ISSUE TITLE
NULL under $params['context']['resource']['file']

### ISSUE THREAD

**Issue by danielczestki** [BlackbitDigitalCommerce/pimcore-data-director#25]
Hi.

I am importing one xlsx file.
It was working fine but now - not.

The problem we have with this code:

On last call I want the get the name of imported file:
```
if ($params['lastCall']) {
    $file = $params['context']['resource']['file'];
    ....
```
    
But when I debug it it looks it has NULL - why ?

```
[WARNING] Additional output during run: 
array(3) {
  ["dataportId"]=>
  string(2) "55"
  ["resource"]=>
  array(2) {
    ["file"]=>
    NULL
    ["locale"]=>
    string(2) "en"
  }
  ["logs"]=>
  string(0) ""
}
```

**Comment by danielczestki** [comment]
Also dataport is not show up under right click menu on Asset.

Configuration:
![obraz](https://user-images.githubusercontent.com/2109480/163180671-67926661-64ce-4c16-b748-46d55f58d720.png)

Right click:

![obraz](https://user-images.githubusercontent.com/2109480/163180887-d0eaec04-a2eb-4423-b5a9-cb8799e91dc7.png)

**Comment by BlackbitNeueMedien** [comment]
Should also be solved in 2.8.5. The parser simply did not get informed about the import file.

**Comment by danielczestki** [comment]
Working! Thanks.

**Comment by BlackbitNeueMedien** [comment]
`$params['context']['resource']['file']` contains the used import source. This can be a folder, a glob expression, a single file or a URL etc.
If you want to know from which file a certain raw data item came from, please add a raw data field `__source`

Here is a quote from the documentation:
> You can specify a folder path as import source instead of a single file. In this case files in this folder (and subfolders) are imported subsequently (sorted by modification time - oldest first). Already imported files are stored in an `archive` folder within the import folder.
>
> In addition to the source file fields you can use the field `__source` to obtain the source file name. This can be useful if you want to process the source file name in the object import (e.g. to call a dependent import with the same import file).
