### ISSUE TITLE
Bug: unZIPping is impossible for StreamingXmlParser

### ISSUE THREAD

**Issue by kaurov** [BlackbitDigitalCommerce/pimcore-data-director#31]
\Blackbit\DataDirectorBundle\lib\Pim\Parser\ResourceBasedParser::extractFile

` ($this instanceof XmlParser && File::getFileExtension($fileName) === 'xml') ||`

should be replaced with
```
 ($this instanceof XmlParser && File::getFileExtension($fileName) === 'xml') ||
 ($this instanceof StreamingXmlParser && File::getFileExtension($fileName) === 'xml') ||
```

**Comment by BlackbitNeueMedien** [comment]
Sorry, have overseen this. You are completely right, thanks. 
Fixed in 3.0.4.
