### ISSUE TITLE
Bug: extracting crashes if there is no 'xmlns' node.

### ISSUE THREAD

**Issue by kaurov** [BlackbitDigitalCommerce/pimcore-data-director#32]
\Blackbit\DataDirectorBundle\lib\Pim\Parser\XmlParser::getDomXPath

extracting crashes if there is no 'xmlns' node.
`$root->removeAttributeNS($root->getAttributeNode('xmlns')->nodeValue, '');`

**Comment by BlackbitNeueMedien** [comment]
Fixed in 3.0.1
