### ISSUE TITLE
Filtering canceled jobs on wrong list

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#42]
![obraz](https://user-images.githubusercontent.com/7449124/178434007-9e79f4de-eff6-4bdd-9719-42101aba8292.png)

Canceled jobs are under

![obraz](https://user-images.githubusercontent.com/7449124/178434225-d7f3ac6e-7136-4a9c-8c20-d51ca0892000.png)

**Comment by BlackbitNeueMedien** [comment]
Thanks. Is fixed in 3.1
