### ISSUE TITLE
Cant use "set" as attribute because of SQL Syntax error 

### ISSUE THREAD

**Issue by AndreasEisenbergerDGTLS** [BlackbitDigitalCommerce/pimcore-data-director#47]
This is the query which has an syntax error because "set" is a reserved word.

INSERT INTO object_store_Product (oo_id,set) VALUES (1,2) ON DUPLICATE KEY UPDATE oo_id=VALUES(oo_id),set=VALUES(set)

If the query would wrap the column names in backticks it should work, no more syntax error:

INSERT INTO object_store_Product (oo_id,`set`) VALUES (1,2) ON DUPLICATE KEY UPDATE oo_id=VALUES(oo_id),`set`=VALUES(`set`)

How to recreate:
1. Create Pimcore class and add "set" as a checkbox (in our case)
2. Create dataport and assign any value to "set"
3. "Start import" will produce this SQL syntax error in the log

It would be great if you could look into this and create a fix for this.

Best regards Andreas

**Comment by BlackbitNeueMedien** [comment]
Which DD version are you using? Just tested it with 3.1 and there the problem does not occur.

**Comment by AndreasEisenbergerDGTLS** [comment]
We are using 3.0.5

**Comment by BlackbitNeueMedien** [comment]
Was fixed in 3.0.6 but I would recommend to update to latest stable.
