### ISSUE TITLE
No actual documentation. README

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#5]
I try to setup pipe line object import.
I tried to use tutorial from youtube but it looks they are outdated.

I can not find in documentation what is it for:
![image](https://user-images.githubusercontent.com/7449124/149325494-45b3ce3f-86bf-4a87-82c8-ea5a7b58cb9f.png)

Second. My setup does not work. Products are not created under Categories.
Where can I find actual documentation to setup it.

**Comment by BlackbitNeueMedien** [comment]
The up-to-date documentation is available at https://pimcore.blackbit.de/Blackbit/1.pimcore/Handb%C3%BCcher/Ultima-Import-Bundle.pdf, please search for "Dynamic import resource path / URL - parametrized imports and exports".

In short:
With parameters you can fill placeholder variables in your import resource path and you can use parameters to change the logic in your callback functions by accessing `$params['request']`

Please write to info@blackbit.de if you need further support. Then we can set up this import pipeline together via screen-sharing.

**Comment by betterapp** [comment]
But this is payed help. Thats really great that youtube tutorial is not related with latest DD version, and setting up base on this tutorial does not work.

**Comment by betterapp** [comment]
![image](https://user-images.githubusercontent.com/7449124/149330091-de69f170-ac7a-4f55-8d67-4f7784afa015.png)

Sorry but I can not found any information about this in latest document.

**Comment by betterapp** [comment]
@BlackbitNeueMedien 

When I clik on "Import raw data to object" button and klick Yes on confirm alert
it open new tab in the browser with url:
/api/rest/export/DanielCategory?skipExtract=1&force=0

Why ? This should work like that ?

**Comment by BlackbitNeueMedien** [comment]
Yes, support needs to be paid. Do you work for free?
We always reacted within minutes to your questions - and never billed you anything. But now your questions are about the implementation for a concrete project. This support cannot be offered for free, sorry.
