### ISSUE TITLE
BUG: implode cannot return imageGallery items pathes

### ISSUE THREAD

**Issue by kaurov** [BlackbitDigitalCommerce/pimcore-data-director#50]
I created dataDirector export dataport with raw field:
**imageGallery:Items:implode:Thumbnail#somename:Path** 
It returns nothing '';

Athoug there is data in the gallery: if I change it to 
**imageGallery:Items**
then I get 
**["/tmp/photo1.jpeg", "/tmp/photo2.jpeg"]**

How can I get list of urls to asset images or/and their thumbnails?

**Comment by BlackbitDevs** [comment]
Please try:
`imageGallery:each:(Thumbnail#sommer_category:Path):implode`

Your current approach fetches the items (`imageGallery:Items` will return an array of `HotspotImage` objects) and then implodes them to a string - this does not work.

**Comment by kaurov** [comment]
Thank you very much!
