### ISSUE TITLE
Put Datadirector link in the menu on the top level like the datahub is

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#53]
Is it possible to put Datadirector link in the menu on the top level like the datahub is ?
![image](https://user-images.githubusercontent.com/7449124/194279553-27c75775-4454-4add-8407-448c31db466b.png)

Currently the datadirector icon is Under "Settings" menu.

**Comment by BlackbitDevs** [comment]
Yes, beginning with version 3.2 the Data Director main menu item is on the top level.
Together with the favourite dataports feature this allows to easily access the most important dataports (favourites can be configured on a role-basis, so users of role A can have different favourites then users of role B):
<img width="269" alt="Bildschirmfoto 2022-10-06 um 12 51 31" src="https://user-images.githubusercontent.com/8749138/194295043-33861928-15a7-4300-af32-6b905356cd14.png">
