### ISSUE TITLE
Skip update specific field on some condition

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#55]
In documentation there is only information about skipping all Item update by return null in one of Key field.

But I need to skip update some specific field os some conditions but the rest I need to update.

As I see if I return "false" from field settings the field is not updated. This works for relation field.
But how can I skip update other field type - for example boolean, or text ?

Is it possible ?

**Comment by BlackbitDevs** [comment]
Yes, this is possible: You can `return $params['currentValue']` in the field's callback function when you want to keep the current value, e.g.
```php
if(strlen($params['value']) > strlen($params['currentValue']) {
  return $params['value'];
} else {
  return $params['currentValue'];
}
```

**Comment by betterapp** [comment]
Working - thanks
