### ISSUE TITLE
matches hash of raw data values

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#6]
Case

I have setup data port for update data.
Prepared XML file.

When I use this file for update data direct from PimCore Panel everything is ok.

When I use the same XML file and try to use API for update data I got error:

`[INFO] Importing raw item 16984
[DEBUG] Fetching item from database
[INFO] Skipping ArticleNumber=12345 because object property "importhash_5" of object #29920 matches hash of raw data values
[INFO] Importing raw item 16985
[DEBUG] Fetching item from database
[INFO] Skipping ArticleNumber=123456 because object property "importhash_5" of object #29921 matches hash of raw data values`

Why for API import DD checks hash if dataport is not defined to do it ?

**Comment by betterapp** [comment]
Looks like need to add **force** parameter with value "1"

Maybe this information could be added 
![image](https://user-images.githubusercontent.com/7449124/152774738-367305bb-c79e-4be4-8abd-8de3f7273a14.png)

**Comment by BlackbitNeueMedien** [comment]
Ok, will add this hint. Thanks for suggestion!
