### ISSUE TITLE
Additional column for attribute mapping tab

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#7]
Hello

Is it possible to add additional column "Attribute Name" and change "Attribute" to "Attribute Label" for Attribute Mapping Tab ?
We use different language for attribute Label and Name and many times it is difficult to map import fields.

Can You make such change ?

![image](https://user-images.githubusercontent.com/7449124/152769671-0dd7226c-9b82-4cce-8ad4-4d3e0998d4bf.png)

**Comment by BlackbitNeueMedien** [comment]
There is a tooltip when you move your cursor over the attribute name if it differs from the title:
<img width="374" alt="Bildschirmfoto 2022-02-08 um 16 43 00" src="https://user-images.githubusercontent.com/8749138/153022325-77a09892-1a5c-445e-bacd-5910e7724bd1.png">

And the search on the top also searches for the real field names, not only the titles / labels (it even searches through the example data).

**Comment by betterapp** [comment]
Ok. Thanks.
