### ISSUE TITLE
Tags assignment custom callback causes exception

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#72]
If you try to assign multiple pimcore Tags, you need to explode the list like for the object relations.
If i add custom callback and click on save:
![image](https://user-images.githubusercontent.com/6016485/214597582-ca32ea4b-4f58-45d3-92de-723111273e77.png)
I get this error:
`<br />
<b>Fatal error</b>:  Nesting level too deep - recursive dependency? in <b>pimcore/vendor/blackbit/data-director/lib/Pim/Item/Importer.php</b> on line <b>3065</b><br />
{"success":false,"message":"Error: Nesting level too deep - recursive dependency?"}`

How to reproduce:
1.) Create tags cool, sehr cool and wunderbar for example
2.) Create csv file like this:
![image](https://user-images.githubusercontent.com/6016485/214598392-eb74ae15-f209-45e9-9c18-ae7ac4dd1d7e.png)
3.) Create import Dataport for the object of your choice, go to attribute mapping and try to use the callback like in screenshot on tags and save the config.

Expected behaviour:  Tags are splited in array and shown in example result
Current behaviour: Exception occures

Data director version: 3.2.25

**Comment by BlackbitDevs** [comment]
Thanks for your report. Have it fixed in just released 3.2.35.

**Comment by ascheider** [comment]
@BlackbitDevs Hey thanks,

explode, works fine now
![image](https://user-images.githubusercontent.com/6016485/216560385-6aa9b11c-952a-4516-918e-3da22f93044a.png)
But the tags are nor assigned to the product after the import. Do i miss something here?
Import Log:
![image](https://user-images.githubusercontent.com/6016485/216560841-da5acb1c-fc4b-40c3-aaa4-993bf29efdf5.png)
Another question, is it possible to import Tags hierarchical? I can select target class, but don't see the possibility to import tags.
Appreciate your help. Thanks!

**Comment by BlackbitDevs** [comment]
The log preview may be misleading here. Can you check if the tags are really not assigned when you open the object and check the "Tags" tab?

Yes, you can import tags hierarchy. Here is an excerpt from the [manual]:
> Tags
You can import one or multiple [tags](https://pimcore.com/docs/latest/Development_Documentation/Tools_and_Features/Tags.html). Tag levels should be separated by /. You can either just assign a raw data field or use a callback function like this
`return ['Tag-Name','hierarchical/tag'];`
Tags which do not exist yet, get automatically created.

So in your case, you could `return ['Attributes/wunderbar', 'Attributes/cool', 'Really/deep/tag/nesting'];`

**Comment by BlackbitDevs** [comment]
Tested with version 3.3:

Log says:
<img width="418" alt="Bildschirmfoto 2023-02-06 um 12 21 39" src="https://user-images.githubusercontent.com/8749138/216959254-ede3cf29-31d3-436b-aae7-8c3b5804737d.png">

Tag panel in object:
<img width="693" alt="Bildschirmfoto 2023-02-06 um 12 22 02" src="https://user-images.githubusercontent.com/8749138/216959250-274c4eb0-fddb-4a60-85c4-f43746f94043.png">

**Comment by ascheider** [comment]
@BlackbitDevs Hi,

no the tags are created, but not assigned.
I'm little confused, i can not see the Version 3.3 in Bitbucket, only 3.2.36 which i'm using currently.
I debug a little bit and output the data where tags are added:
![image](https://user-images.githubusercontent.com/6016485/217189432-d48f2a65-4864-4839-a7f8-7dfc634a7546.png)
I attached the output here:
[dump_object.txt](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/10672909/dump_object.txt)
As u can see, the $cachedItem['tags'] is empty on this point, so the tags are not assigned to the object.
Here is my config and csv file:
[Archiv.zip](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/10672918/Archiv.zip)
I'm using pimcore v10.5.10.

**Comment by BlackbitDevs** [comment]
Sorry, forgot to tag 3.3.0. Now it is available.
But I have also created 3.2.37 which includes the bugfix from 3.3 concerning tag import.

**Comment by ascheider** [comment]
@BlackbitDevs Thank you very much, the version 3.2.37 solved the issue. The tags are now assigned 👍
