### ISSUE TITLE
[BUG] Fail to Install the DataDirector with the Newest Pimcore Version.

### ISSUE THREAD

**Issue by luka-jukic** [BlackbitDigitalCommerce/pimcore-data-director#79]
When I try to install DataDirector with the latest Pimcore version, the installation does not complete.

- Pimcore Version: 10.5.17
- DD Version : 3.2.27 / 3.3.30 (I have not tested other versions)
- All migrations are completed
- MetaData Sync is up to date

Follow up point leads to:

FIle: Blackbit\DataDirectorBundle\Tools\Installer;

I have replaced the following lines (152 - 159):
![Issue](https://user-images.githubusercontent.com/40577324/221192430-876b33f3-2400-4879-acc8-3b2ee3cda7eb.png)

If I comment out these lines and replace them with 'return true;' it works as expected.
![quick fix](https://user-images.githubusercontent.com/40577324/221192777-a6e13aed-97f5-4fe6-8cbb-c79bf4c2d330.png)

Unfortunately, I did not get around to locating the problem more precisely. I hope you can do something with it.

**Comment by BlackbitDevs** [comment]
Thanks for your report.

What is the latest migration which you have in the `migration_versions` table? I wonder if `the installation does not complete` refers to a long-running migration (which now may not have been executed). Please compare the latest migration version in database to the latest file in `vendor/blackbit/data-director/Migrations`.

Alternatively, what is the output of `bin/console doctrine:migrations:up-to-date --prefix=Blackbit\DataDirectorBundle`?

**Comment by luka-jukic** [comment]
The fault was on our side. The PHP binary was not specified correctly. Sorry for any inconvenience.
