### ISSUE TITLE
Brick with localized field with many to many object relation does not work

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#80]
Pimcore 10.5.10
Data Director: 3.2.37

How to reproduce:

Zip:
[Archiv.zip](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/10825456/Archiv.zip)

Import 'Test' class and Import 'Import' Brick from zip.
Create 2 Test objects in root folder:
![image](https://user-images.githubusercontent.com/6016485/221205399-f5d9a6ad-9ac1-4a71-95a4-7d327f116c83.png)
Import Data Director Config from zip.
Upload csv file:
[relation-brick-import.csv](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/10825385/relation-brick-import.csv)
Run import.
Expected Result:
Relation Object is assigned in Test relation brick in german language.
Actual result: Exception
Trace:
[stack-trace.txt](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/files/10825400/stack-trace.txt)
If i assign relation object manually everything is okay:
![image](https://user-images.githubusercontent.com/6016485/221209234-1cb2a79f-8498-4d4d-a032-319832b6cc27.png)
If i for example create input fields inside localized brick, import works fine, the problem is only with relation field.
Hope it helps to reproduce the issue.

**Comment by BlackbitDevs** [comment]
Thanks for your brillant instructions of how to reproduce the error. Is fixed in 3.3.1.

**Comment by BlackbitDevs** [comment]
One little addition, @ascheider: Please be aware that the mapping field `path` is for the *parent element*. It is not to map the *full* path (which consists of path and key (= object name). 
For this reason your example import currently throws an `ALERT: Cannot set parent object to itself`.
