### ISSUE TITLE
Excel (xlsx) export

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#86]
Is there any template/possibility for excel export?
I can only see csv, xml, html and other formats.

**Comment by ascheider** [comment]
@BlackbitDevs No i do not have any problems. The customer and his coworkers just likes excel and works with the format everywhere.
Can you please sent the estimation to: info at scope01.com (If you want to integrate it in the bundle)
Thank you.

**Comment by BlackbitDevs** [comment]
> Can you please sent the estimation to: info at scope01.com (If you want to integrate it in the bundle)

Sorry, have not seen your comment. Is your requirement still valid? We will send you the offer ASAP.

**Comment by ascheider** [comment]
@BlackbitDevs No problem. Yes, please send the offer. Thanks!

**Comment by BlackbitDevs** [comment]
@ascheider We have implemented the result callback function template for Excel export in version 3.5.x-dev. Is it ok for you to use this (not yet released) version or shall I create a separate version of 3.4 which includes the Excel template?

**Comment by ascheider** [comment]
@BlackbitDevs Hi, cool.
the customer is currently using 3.4
If its not big effort for you, than please merge it in 3.4.
Thank you!

**Comment by BlackbitDevs** [comment]
Is now also included in 3.4.6.

**Comment by ascheider** [comment]
@BlackbitDevs Hi,

i just tried to the test feature.
In template selection, the excel name template name 'pim.mapping.template.rawdata_as_excel' is not translated:
![Bildschirmfoto 2023-07-03 um 10 27 56](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/74d98681-09c5-4fff-974e-4f590bcf0128)
Also async auto refresh request fails:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/b4edae82-b042-48ee-ab82-9f7584814ed2)

Tested with 3.4.6
Pimcore: 10.5.23

**Comment by BlackbitDevs** [comment]
Sorry, forgot the translations. Have just released 3.4.7.
Have successfully tested it locally. I wonder a bit about the `ERR_CONNECTION_REFUSED` error. If this still happens with 3.4.7, do you see any more information in the `Console` tab? Because I recently have fixed a bug where HTTP URLs got called for a project which is accessible only via HTTPS.

**Comment by ascheider** [comment]
@BlackbitDevs
The translation is fixed. Thanks!
i have the same problem with 3.4.7. Only this url is called with https
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/de3f4f23-ba45-42bb-8fce-2677dd95e263)
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/597ee29a-ee67-4f92-8d97-8acf68149536)

All another data director urls are correct and called with http
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/42197da6-13cb-4a3c-890c-1dc22f81e433)

**Comment by BlackbitDevs** [comment]
Before wasting some more version numbers, can you please try if it works now with 3.4.x-dev?

**Comment by ascheider** [comment]
@BlackbitDevs Tried with the 3.4 branch, which is 3.4.8, but have still the issue. Doe you have a commit link, where you fixed the https issue, then i can try to debug the problem on my machine. If i search for reloadUrl in the bundle, i do not find the place, where it's build.

**Comment by ascheider** [comment]
@BlackbitDevs Do you have feedback for me? Thanks!

**Comment by BlackbitDevs** [comment]
Should be https://bitbucket.org/blackbitwerbung/pimcore-plugins-data-director/commits/9afd0907aadb8c76d30319d5520551e179a108a6

**Comment by ascheider** [comment]
@BlackbitDevs Okay, got ist.
The function getHostUrl in htdocs/vendor/blackbit/data-director/lib/Pim/Helper.php builds url always with https.
If i change 
` self::$hostUrl = Tool::getHostUrl('https', self::getRequest());`
to:
`
   if (self::getRequest()->getScheme() === 'http') {
                self::$hostUrl = Tool::getHostUrl('http', self::getRequest());
            } else {
                self::$hostUrl = Tool::getHostUrl('https', self::getRequest());
            }
`
Than it works fine, if request protocol is http, http is used, otherwise like before:
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/6016485/45c9b393-3bb3-45e5-b384-5a6ad94409d7)
Can you please integrate it in 3.4?
Thanks!
The excel file after fix and export look for me fine!

**Comment by BlackbitDevs** [comment]
Sorry, you are right. I wrongly assumed that `Pimcore\Tool::getHostUrl` only uses the given protocol if there is no HTTP request available. But in fact it overwrites the request's protocol.
Fixed in 3.4.9.
